version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    container_name: ts-rest-api
    environment:
      - PORT=${PORT}
      - DB_URI=${DB_URI}
    ports:
      - ${PORT}:${PORT}

  db:
    image: mongo:6
    restart: always
    container_name: ts-rest-api-db
    environment:
      - MONGO_DATABASE=${MONGO_DATABASE}
    volumes:
      - ./data:/data/db