version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    container_name: ts-rest-api
    environment:
      - PORT=${PORT}
      - DB_URI=${DB_URI}
    ports:
      - ${PORT}:${PORT}
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGODB_DATABASE= ts-rest-api
    volumes:
      - ./mongo:/data/db

  # db:
  #   image: mongo
  #   restart: always
  #   container_name: ts-rest-api-db
  #   environment:
  #     - MONGO_DATABASE=${MONGO_DATABASE}
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./data:/data/db